openai:
  api_key: "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"
  endpoint: "https://api.openai.com/v1/chat/completions"
  model: "gpt-4"
  prompts:
    assistant: "You are a helpful assistant."
    dev: " Respond briefly and concisely short cmd  as table"
    tutor: "You are a patient tutor explaining technical topics to beginners."

